name: Code Golf

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update rust
        run: |
          rustup update
          cargo --version
          rustc --version

      - name: Execute unit tests
        run: cargo test --verbose
